#include "pch.h"

#include "../msverrorcodes.h"

#include "MsvErrorTestConstants.h"


MsvErrorCode CheckAndReturnErrorCode(MsvErrorCode errorCode)
{
	MSV_RETURN_FAILED(errorCode);

	return MSV_SUCCESS;
}

TEST(MsvErrorTest, MSV_SUCCESS_ShouldSucceeded)
{
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_SUCCESS));
	EXPECT_FALSE(MSV_FAILED(MSV_SUCCESS));
}

TEST(MsvErrorTest, ItShouldBePossibleToAssignInMacros)
{
	MsvErrorCode errorcode = MSV_SUCCESS;
	EXPECT_TRUE(MSV_SUCCEEDED(errorcode = MSV_SUCCESS));
	EXPECT_FALSE(MSV_FAILED(errorcode = MSV_SUCCESS));
}

TEST(MsvErrorTest, ItShouldDetectSuccessAsSuccess)
{
	EXPECT_TRUE(MSV_IS_SUCCESS(MSV_SUCCESS_MIN));
	EXPECT_TRUE(MSV_IS_SUCCESS(MSV_SUCCESS_MIDDLE));
	EXPECT_TRUE(MSV_IS_SUCCESS(MSV_SUCCESS_MAX));

	EXPECT_FALSE(MSV_IS_INFO(MSV_SUCCESS_MIN));
	EXPECT_FALSE(MSV_IS_INFO(MSV_SUCCESS_MIDDLE));
	EXPECT_FALSE(MSV_IS_INFO(MSV_SUCCESS_MAX));

	EXPECT_FALSE(MSV_IS_WARN(MSV_SUCCESS_MIN));
	EXPECT_FALSE(MSV_IS_WARN(MSV_SUCCESS_MIDDLE));
	EXPECT_FALSE(MSV_IS_WARN(MSV_SUCCESS_MAX));

	EXPECT_FALSE(MSV_IS_ERROR(MSV_SUCCESS_MIN));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_SUCCESS_MIDDLE));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_SUCCESS_MAX));
}

TEST(MsvErrorTest, ItShouldDetectInfoAsInfo)
{
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_INFO_MIN));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_INFO_MIDDLE));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_INFO_MAX));

	EXPECT_TRUE(MSV_IS_INFO(MSV_INFO_MIN));
	EXPECT_TRUE(MSV_IS_INFO(MSV_INFO_MIDDLE));
	EXPECT_TRUE(MSV_IS_INFO(MSV_INFO_MAX));

	EXPECT_FALSE(MSV_IS_WARN(MSV_INFO_MIN));
	EXPECT_FALSE(MSV_IS_WARN(MSV_INFO_MIDDLE));
	EXPECT_FALSE(MSV_IS_WARN(MSV_INFO_MAX));

	EXPECT_FALSE(MSV_IS_ERROR(MSV_INFO_MIN));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_INFO_MIDDLE));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_INFO_MAX));
}

TEST(MsvErrorTest, ItShouldDetectWarnAsWarn)
{
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_WARN_MIN));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_WARN_MIDDLE));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_WARN_MAX));

	EXPECT_FALSE(MSV_IS_INFO(MSV_WARN_MIN));
	EXPECT_FALSE(MSV_IS_INFO(MSV_WARN_MIDDLE));
	EXPECT_FALSE(MSV_IS_INFO(MSV_WARN_MAX));

	EXPECT_TRUE(MSV_IS_WARN(MSV_WARN_MIN));
	EXPECT_TRUE(MSV_IS_WARN(MSV_WARN_MIDDLE));
	EXPECT_TRUE(MSV_IS_WARN(MSV_WARN_MAX));

	EXPECT_FALSE(MSV_IS_ERROR(MSV_WARN_MIN));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_WARN_MIDDLE));
	EXPECT_FALSE(MSV_IS_ERROR(MSV_WARN_MAX));
}

TEST(MsvErrorTest, ItShouldDetectErrorAsError)
{
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_ERROR_MIN));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_ERROR_MIDDLE));
	EXPECT_FALSE(MSV_IS_SUCCESS(MSV_ERROR_MAX));

	EXPECT_FALSE(MSV_IS_INFO(MSV_ERROR_MIN));
	EXPECT_FALSE(MSV_IS_INFO(MSV_ERROR_MIDDLE));
	EXPECT_FALSE(MSV_IS_INFO(MSV_ERROR_MAX));

	EXPECT_FALSE(MSV_IS_WARN(MSV_ERROR_MIN));
	EXPECT_FALSE(MSV_IS_WARN(MSV_ERROR_MIDDLE));
	EXPECT_FALSE(MSV_IS_WARN(MSV_ERROR_MAX));

	EXPECT_TRUE(MSV_IS_ERROR(MSV_ERROR_MIN));
	EXPECT_TRUE(MSV_IS_ERROR(MSV_ERROR_MIDDLE));
	EXPECT_TRUE(MSV_IS_ERROR(MSV_ERROR_MAX));
}

TEST(MsvErrorTest, ItShouldSucceededForSuccess)
{
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_SUCCESS_MIN));
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_SUCCESS_MIDDLE));
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_SUCCESS_MAX));

	EXPECT_FALSE(MSV_FAILED(MSV_SUCCESS_MIN));
	EXPECT_FALSE(MSV_FAILED(MSV_SUCCESS_MIDDLE));
	EXPECT_FALSE(MSV_FAILED(MSV_SUCCESS_MAX));
}

TEST(MsvErrorTest, ItShouldSucceededForInfos)
{
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_INFO_MIN));
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_INFO_MIDDLE));
	EXPECT_TRUE(MSV_SUCCEEDED(MSV_INFO_MAX));

	EXPECT_FALSE(MSV_FAILED(MSV_INFO_MIN));
	EXPECT_FALSE(MSV_FAILED(MSV_INFO_MIDDLE));
	EXPECT_FALSE(MSV_FAILED(MSV_INFO_MAX));
}

TEST(MsvErrorTest, ItShouldFailedForWarnings)
{
	EXPECT_TRUE(MSV_FAILED(MSV_WARN_MIN));
	EXPECT_TRUE(MSV_FAILED(MSV_WARN_MIDDLE));
	EXPECT_TRUE(MSV_FAILED(MSV_WARN_MAX));

	EXPECT_FALSE(MSV_SUCCEEDED(MSV_WARN_MIN));
	EXPECT_FALSE(MSV_SUCCEEDED(MSV_WARN_MIDDLE));
	EXPECT_FALSE(MSV_SUCCEEDED(MSV_WARN_MAX));
}

TEST(MsvErrorTest, ItShouldFailedForErrors)
{
	EXPECT_TRUE(MSV_FAILED(MSV_ERROR_MIN));
	EXPECT_TRUE(MSV_FAILED(MSV_ERROR_MIDDLE));
	EXPECT_TRUE(MSV_FAILED(MSV_ERROR_MAX));

	EXPECT_FALSE(MSV_SUCCEEDED(MSV_ERROR_MIN));
	EXPECT_FALSE(MSV_SUCCEEDED(MSV_ERROR_MIDDLE));
	EXPECT_FALSE(MSV_SUCCEEDED(MSV_ERROR_MAX));
}

TEST(MsvErrorTest, ItShouldReturnSuccessForSuccess)
{
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_SUCCESS_MIN), MSV_SUCCESS);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_SUCCESS_MIDDLE), MSV_SUCCESS);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_SUCCESS_MAX), MSV_SUCCESS);
}

TEST(MsvErrorTest, ItShouldReturnSuccessForInfos)
{
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_INFO_MIN), MSV_SUCCESS);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_INFO_MIDDLE), MSV_SUCCESS);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_INFO_MAX), MSV_SUCCESS);
}

TEST(MsvErrorTest, ItShouldReturnErrorCodeForWarnings)
{
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_WARN_MIN), MSV_WARN_MIN);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_WARN_MIDDLE), MSV_WARN_MIDDLE);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_WARN_MAX), MSV_WARN_MAX);
}

TEST(MsvErrorTest, ItShouldReturnErrorCodeForErrors)
{
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_ERROR_MIN), MSV_ERROR_MIN);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_ERROR_MIDDLE), MSV_ERROR_MIDDLE);
	EXPECT_EQ(CheckAndReturnErrorCode(MSV_ERROR_MAX), MSV_ERROR_MAX);
}

TEST(MsvErrorTest, ItShouldNotBreakForSuccess)
{
	int i = 0;
	for (; i < 2; ++i)
	{
		MSV_BREAK_FAILED(MSV_SUCCESS_MIN);
		MSV_BREAK_FAILED(MSV_SUCCESS_MIDDLE);
		MSV_BREAK_FAILED(MSV_SUCCESS_MAX);
	}

	EXPECT_EQ(i, 2);
}

TEST(MsvErrorTest, ItShouldNotBreakForInfos)
{
	int i = 0;
	for (; i < 2; ++i)
	{
		MSV_BREAK_FAILED(MSV_INFO_MIN);
		MSV_BREAK_FAILED(MSV_INFO_MIDDLE);
		MSV_BREAK_FAILED(MSV_INFO_MAX);
	}

	EXPECT_EQ(i, 2);
}

TEST(MsvErrorTest, ItShouldBreakForWarnings)
{
	int i = 0;

	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_WARN_MIN); }
	EXPECT_EQ(i, 0);

	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_WARN_MIDDLE); }
	EXPECT_EQ(i, 0);

	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_WARN_MAX); }
	EXPECT_EQ(i, 0);
}

TEST(MsvErrorTest, ItShouldBreakForErrors)
{
	int i = 0;

	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_ERROR_MIN); }
	EXPECT_EQ(i, 0);
	
	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_ERROR_MIDDLE); }
	EXPECT_EQ(i, 0);
	
	for (; i < 2; ++i) { MSV_BREAK_FAILED(MSV_ERROR_MAX); }
	EXPECT_EQ(i, 0);
}

TEST(MsvErrorTest, ItShouldNotContinueForSuccess)
{
	int i = 0;
	while (i < 2)
	{
		MSV_CONTINUE_FAILED(MSV_SUCCESS_MIN);
		MSV_CONTINUE_FAILED(MSV_SUCCESS_MIDDLE);
		MSV_CONTINUE_FAILED(MSV_SUCCESS_MAX);
		++i;
	}

	EXPECT_EQ(i, 2);
}

TEST(MsvErrorTest, ItShouldNotContinueForInfos)
{
	int i = 0;
	while (i < 2)
	{
		MSV_CONTINUE_FAILED(MSV_INFO_MIN);
		MSV_CONTINUE_FAILED(MSV_INFO_MIDDLE);
		MSV_CONTINUE_FAILED(MSV_INFO_MAX);
		++i;
	}

	EXPECT_EQ(i, 2);
}

TEST(MsvErrorTest, ItShouldContinueForWarnings)
{
	int i = 0;

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_WARN_MIN); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_WARN_MIDDLE); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_WARN_MAX); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);
}

TEST(MsvErrorTest, ItShouldContinueForErrors)
{
	int i = 0;

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_ERROR_MIN); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_ERROR_MIDDLE); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);

	for (; i < 2; ++i) { MSV_CONTINUE_FAILED(MSV_ERROR_MAX); EXPECT_TRUE(false); }
	EXPECT_EQ(i, 2);
}
